### ISSUE TITLE
login error

### ISSUE THREAD

**Issue by encyptAES** [enricoangelon/MCBEProxy#1]
Warning: zlib_decode(): data error in C:\Users\kanep\Desktop\MCBEProxy-main\vendor\pocketmine\pocketmine-mp\src\pocketmine\network\mcpe\protocol\BatchPacket.php on line 65

Fatal error: Uncaught TypeError: pocketmine\utils\BinaryStream::__construct(): Argument #1 ($buffer) must be of type string, bool given, called in C:\Users\kanep\Desktop\MCBEProxy-main\vendor\pocketmine\pocketmine-mp\src\pocketmine\network\mcpe\protocol\BatchPacket.php on line 101 and defined in C:\Users\kanep\Desktop\MCBEProxy-main\vendor\pocketmine\binaryutils\src\BinaryStream.php:40
Stack trace:
#0 C:\Users\kanep\Desktop\MCBEProxy-main\vendor\pocketmine\pocketmine-mp\src\pocketmine\network\mcpe\protocol\BatchPacket.php(101): pocketmine\utils\BinaryStream->__construct(false)
#1 C:\Users\kanep\Desktop\MCBEProxy-main\src\proxy\ConnectedServerHandler.php(63): pocketmine\network\mcpe\protocol\BatchPacket->getPackets()
#2 C:\Users\kanep\Desktop\MCBEProxy-main\src\proxy\ServerSession.php(124): proxy\ConnectedServerHandler->handleMinecraft(Object(raklib\protocol\EncapsulatedPacket))
#3 C:\Users\kanep\Desktop\MCBEProxy-main\src\proxy\NetworkSession.php(124): proxy\ServerSession->handleEncapsulated(Object(raklib\protocol\EncapsulatedPacket))
#4 C:\Users\kanep\Desktop\MCBEProxy-main\src\proxy\NetworkSession.php(67): proxy\NetworkSession->handleConnectedDatagram('\x80\x06\x00\x00`\x00\xA8\x06\x00\x00\x01\x00\x00\x00\xFE...')
#5 C:\Users\kanep\Desktop\MCBEProxy-main\src\proxy\ServerSession.php(66): proxy\NetworkSession->handle('\x80\x06\x00\x00`\x00\xA8\x06\x00\x00\x01\x00\x00\x00\xFE...')
#6 C:\Users\kanep\Desktop\MCBEProxy-main\src\proxy\ProxyServer.php(58): proxy\ServerSession->readPacket()
#7 C:\Users\kanep\Desktop\MCBEProxy-main\loader.php(20): proxy\ProxyServer->start()
#8 {main}
  thrown in C:\Users\kanep\Desktop\MCBEProxy-main\vendor\pocketmine\binaryutils\src\BinaryStream.php on line 40

**Comment by enricoangelon** [comment]
What server were you trying to join? Is it encrypted?

**Comment by enricoangelon** [comment]
Yep confirmed, that's due to encryption... will be implemented really soon!!

**Comment by encyptAES** [comment]
thanks
